// <auto-generated />
using System;
using CardDuel.ServerApi.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CardDuel.ServerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420192008_ConvertToSnakeCase")]
    partial class ConvertToSnakeCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.AbilityDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AbilityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ability_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<int>("TargetSelectorKind")
                        .HasColumnType("integer")
                        .HasColumnName("target_selector_kind");

                    b.Property<int>("TriggerKind")
                        .HasColumnType("integer")
                        .HasColumnName("trigger_kind");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId")
                        .IsUnique();

                    b.ToTable("abilities", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.AuditLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("resource");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("resource_id");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("UserId");

                    b.HasIndex("Resource", "ResourceId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.CardAbilityDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AbilityDefinitionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ability_definition_id");

                    b.Property<string>("CardDefinitionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_definition_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id");

                    b.HasIndex("AbilityDefinitionId");

                    b.HasIndex("CardDefinitionId", "Sequence")
                        .IsUnique();

                    b.ToTable("card_abilities", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.CardDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AllowedRow")
                        .HasColumnType("integer")
                        .HasColumnName("allowed_row");

                    b.Property<int>("Armor")
                        .HasColumnType("integer")
                        .HasColumnName("armor");

                    b.Property<int>("Attack")
                        .HasColumnType("integer")
                        .HasColumnName("attack");

                    b.Property<int>("CardFaction")
                        .HasColumnType("integer")
                        .HasColumnName("card_faction");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("card_id");

                    b.Property<int>("CardRarity")
                        .HasColumnType("integer")
                        .HasColumnName("card_rarity");

                    b.Property<int>("CardType")
                        .HasColumnType("integer")
                        .HasColumnName("card_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DefaultAttackSelector")
                        .HasColumnType("integer")
                        .HasColumnName("default_attack_selector");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<int>("Health")
                        .HasColumnType("integer")
                        .HasColumnName("health");

                    b.Property<bool>("IsLimited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_limited");

                    b.Property<int>("ManaCost")
                        .HasColumnType("integer")
                        .HasColumnName("mana_cost");

                    b.Property<int>("TurnsUntilCanAttack")
                        .HasColumnType("integer")
                        .HasColumnName("turns_until_can_attack");

                    b.Property<int?>("UnitType")
                        .HasColumnType("integer")
                        .HasColumnName("unit_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.EffectDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AbilityDefinitionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ability_definition_id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EffectKind")
                        .HasColumnType("integer")
                        .HasColumnName("effect_kind");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id");

                    b.HasIndex("AbilityDefinitionId", "Sequence")
                        .IsUnique();

                    b.ToTable("effects", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.MatchAction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ActionData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("action_data");

                    b.Property<int>("ActionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("action_number");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("match_id");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player_id");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("MatchId", "ActionNumber")
                        .IsUnique();

                    b.ToTable("match_actions", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.MatchRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("match_id");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<DateTimeOffset?>("Player1DisconnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("player1_disconnected_at");

                    b.Property<string>("Player1Id")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player1_id");

                    b.Property<int?>("Player1RatingAfter")
                        .HasColumnType("integer")
                        .HasColumnName("player1_rating_after");

                    b.Property<int?>("Player1RatingBefore")
                        .HasColumnType("integer")
                        .HasColumnName("player1_rating_before");

                    b.Property<string>("Player1ReconnectToken")
                        .HasColumnType("text")
                        .HasColumnName("player1_reconnect_token");

                    b.Property<DateTimeOffset?>("Player2DisconnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("player2_disconnected_at");

                    b.Property<string>("Player2Id")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player2_id");

                    b.Property<int?>("Player2RatingAfter")
                        .HasColumnType("integer")
                        .HasColumnName("player2_rating_after");

                    b.Property<int?>("Player2RatingBefore")
                        .HasColumnType("integer")
                        .HasColumnName("player2_rating_before");

                    b.Property<string>("Player2ReconnectToken")
                        .HasColumnType("text")
                        .HasColumnName("player2_reconnect_token");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("room_code");

                    b.Property<string>("WinnerId")
                        .HasColumnType("text")
                        .HasColumnName("winner_id");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.HasIndex("Player1Id", "CreatedAt");

                    b.HasIndex("Player2Id", "CreatedAt");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.PlayerDeck", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CardIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_ids");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeckId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deck_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeckId")
                        .IsUnique();

                    b.ToTable("decks", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.PlayerRating", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Losses")
                        .HasColumnType("integer")
                        .HasColumnName("losses");

                    b.Property<int>("RatingValue")
                        .HasColumnType("integer")
                        .HasColumnName("rating_value");

                    b.Property<string>("Region")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("global")
                        .HasColumnName("region");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.HasKey("Id");

                    b.HasIndex("RatingValue")
                        .IsDescending();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ratings", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.ReplayLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ActionData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("action_data");

                    b.Property<int>("ActionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("action_number");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("match_id");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player_id");

                    b.HasKey("Id");

                    b.ToTable("replay_logs", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.UserAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.CardAbilityDefinition", b =>
                {
                    b.HasOne("CardDuel.ServerApi.Infrastructure.Models.AbilityDefinition", "AbilityDefinition")
                        .WithMany("CardAbilities")
                        .HasForeignKey("AbilityDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardDuel.ServerApi.Infrastructure.Models.CardDefinition", "CardDefinition")
                        .WithMany("CardAbilities")
                        .HasForeignKey("CardDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbilityDefinition");

                    b.Navigation("CardDefinition");
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.EffectDefinition", b =>
                {
                    b.HasOne("CardDuel.ServerApi.Infrastructure.Models.AbilityDefinition", "AbilityDefinition")
                        .WithMany("Effects")
                        .HasForeignKey("AbilityDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbilityDefinition");
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.PlayerRating", b =>
                {
                    b.HasOne("CardDuel.ServerApi.Infrastructure.Models.UserAccount", "User")
                        .WithOne("Rating")
                        .HasForeignKey("CardDuel.ServerApi.Infrastructure.Models.PlayerRating", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.AbilityDefinition", b =>
                {
                    b.Navigation("CardAbilities");

                    b.Navigation("Effects");
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.CardDefinition", b =>
                {
                    b.Navigation("CardAbilities");
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.UserAccount", b =>
                {
                    b.Navigation("Rating");
                });
#pragma warning restore 612, 618
        }
    }
}
