// <auto-generated />
using System;
using CardDuel.ServerApi.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CardDuel.ServerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.AbilityDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AbilityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ability_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("AnimationCueId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("animation_cue_id");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conditions_json");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<int>("SkillType")
                        .HasColumnType("integer")
                        .HasColumnName("skill_type");

                    b.Property<int>("TargetSelectorKind")
                        .HasColumnType("integer")
                        .HasColumnName("target_selector_kind");

                    b.Property<int>("TriggerKind")
                        .HasColumnType("integer")
                        .HasColumnName("trigger_kind");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId")
                        .IsUnique();

                    b.ToTable("abilities", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.AuditLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("resource");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("resource_id");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("UserId");

                    b.HasIndex("Resource", "ResourceId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.CardAbilityDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AbilityDefinitionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ability_definition_id");

                    b.Property<string>("CardDefinitionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_definition_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id");

                    b.HasIndex("AbilityDefinitionId");

                    b.HasIndex("CardDefinitionId", "Sequence")
                        .IsUnique();

                    b.ToTable("card_abilities", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.CardDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AllowedRow")
                        .HasColumnType("integer")
                        .HasColumnName("allowed_row");

                    b.Property<int>("Armor")
                        .HasColumnType("integer")
                        .HasColumnName("armor");

                    b.Property<string>("BattlePresentationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("battle_presentation_json");

                    b.Property<int>("Attack")
                        .HasColumnType("integer")
                        .HasColumnName("attack");

                    b.Property<int>("CardFaction")
                        .HasColumnType("integer")
                        .HasColumnName("card_faction");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("card_id");

                    b.Property<int>("CardRarity")
                        .HasColumnType("integer")
                        .HasColumnName("card_rarity");

                    b.Property<int>("CardType")
                        .HasColumnType("integer")
                        .HasColumnName("card_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DefaultAttackSelector")
                        .HasColumnType("integer")
                        .HasColumnName("default_attack_selector");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<int>("Health")
                        .HasColumnType("integer")
                        .HasColumnName("health");

                    b.Property<bool>("IsLimited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_limited");

                    b.Property<int>("ManaCost")
                        .HasColumnType("integer")
                        .HasColumnName("mana_cost");

                    b.Property<int>("TurnsUntilCanAttack")
                        .HasColumnType("integer")
                        .HasColumnName("turns_until_can_attack");

                    b.Property<int?>("UnitType")
                        .HasColumnType("integer")
                        .HasColumnName("unit_type");

                    b.Property<string>("VisualProfilesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("visual_profiles_json");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.EffectDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AbilityDefinitionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ability_definition_id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationTurns")
                        .HasColumnType("integer")
                        .HasColumnName("duration_turns");

                    b.Property<int>("EffectKind")
                        .HasColumnType("integer")
                        .HasColumnName("effect_kind");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<int?>("SecondaryAmount")
                        .HasColumnType("integer")
                        .HasColumnName("secondary_amount");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<int?>("TargetSelectorKindOverride")
                        .HasColumnType("integer")
                        .HasColumnName("target_selector_kind_override");

                    b.HasKey("Id");

                    b.HasIndex("AbilityDefinitionId", "Sequence")
                        .IsUnique();

                    b.ToTable("effects", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.GameRuleset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("CardsDrawnOnTurnStart")
                        .HasColumnType("integer")
                        .HasColumnName("cards_drawn_on_turn_start");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<int>("InitialDrawCount")
                        .HasColumnType("integer")
                        .HasColumnName("initial_draw_count");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<int>("ManaGrantTiming")
                        .HasColumnType("integer")
                        .HasColumnName("mana_grant_timing");

                    b.Property<int>("ManaGrantedPerTurn")
                        .HasColumnType("integer")
                        .HasColumnName("mana_granted_per_turn");

                    b.Property<int>("MaxHeroHealth")
                        .HasColumnType("integer")
                        .HasColumnName("max_hero_health");

                    b.Property<int>("MaxMana")
                        .HasColumnType("integer")
                        .HasColumnName("max_mana");

                    b.Property<string>("RulesetKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ruleset_key");

                    b.Property<int>("StartingHeroHealth")
                        .HasColumnType("integer")
                        .HasColumnName("starting_hero_health");

                    b.Property<int>("StartingMana")
                        .HasColumnType("integer")
                        .HasColumnName("starting_mana");

                    b.Property<int>("StartingSeatIndex")
                        .HasColumnType("integer")
                        .HasColumnName("starting_seat_index");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault");

                    b.HasIndex("RulesetKey")
                        .IsUnique();

                    b.ToTable("game_rulesets", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.GameRulesetSeatOverride", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AdditionalCardsDrawnOnTurnStart")
                        .HasColumnType("integer")
                        .HasColumnName("additional_cards_drawn_on_turn_start");

                    b.Property<int>("AdditionalHeroHealth")
                        .HasColumnType("integer")
                        .HasColumnName("additional_hero_health");

                    b.Property<int>("AdditionalManaPerTurn")
                        .HasColumnType("integer")
                        .HasColumnName("additional_mana_per_turn");

                    b.Property<int>("AdditionalMaxHeroHealth")
                        .HasColumnType("integer")
                        .HasColumnName("additional_max_hero_health");

                    b.Property<int>("AdditionalMaxMana")
                        .HasColumnType("integer")
                        .HasColumnName("additional_max_mana");

                    b.Property<int>("AdditionalStartingMana")
                        .HasColumnType("integer")
                        .HasColumnName("additional_starting_mana");

                    b.Property<string>("GameRulesetId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game_ruleset_id");

                    b.Property<int>("SeatIndex")
                        .HasColumnType("integer")
                        .HasColumnName("seat_index");

                    b.HasKey("Id");

                    b.HasIndex("GameRulesetId", "SeatIndex")
                        .IsUnique();

                    b.ToTable("game_ruleset_seat_overrides", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.MatchAction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ActionData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("action_data");

                    b.Property<int>("ActionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("action_number");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("match_id");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player_id");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("MatchId", "ActionNumber")
                        .IsUnique();

                    b.ToTable("match_actions", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.MatchmakingModeRulesetAssignment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ruleset_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Mode")
                        .IsUnique();

                    b.HasIndex("RulesetId");

                    b.ToTable("matchmaking_mode_ruleset_assignments", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.MatchRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("GameRulesSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("game_rules_snapshot_json");

                    b.Property<string>("GameRulesetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("game_ruleset_id");

                    b.Property<string>("GameRulesetName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("game_ruleset_name");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("match_id");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<DateTimeOffset?>("Player1DisconnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("player1_disconnected_at");

                    b.Property<string>("Player1Id")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player1_id");

                    b.Property<int?>("Player1RatingAfter")
                        .HasColumnType("integer")
                        .HasColumnName("player1_rating_after");

                    b.Property<int?>("Player1RatingBefore")
                        .HasColumnType("integer")
                        .HasColumnName("player1_rating_before");

                    b.Property<string>("Player1ReconnectToken")
                        .HasColumnType("text")
                        .HasColumnName("player1_reconnect_token");

                    b.Property<DateTimeOffset?>("Player2DisconnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("player2_disconnected_at");

                    b.Property<string>("Player2Id")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player2_id");

                    b.Property<int?>("Player2RatingAfter")
                        .HasColumnType("integer")
                        .HasColumnName("player2_rating_after");

                    b.Property<int?>("Player2RatingBefore")
                        .HasColumnType("integer")
                        .HasColumnName("player2_rating_before");

                    b.Property<string>("Player2ReconnectToken")
                        .HasColumnType("text")
                        .HasColumnName("player2_reconnect_token");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("room_code");

                    b.Property<string>("WinnerId")
                        .HasColumnType("text")
                        .HasColumnName("winner_id");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.HasIndex("GameRulesetId");

                    b.HasIndex("Player1Id", "CreatedAt");

                    b.HasIndex("Player2Id", "CreatedAt");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.PlayerDeck", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeckId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deck_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeckId")
                        .IsUnique();

                    b.ToTable("decks", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.DeckCard", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CardDefinitionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_definition_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeckId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deck_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.HasIndex("CardDefinitionId");

                    b.HasIndex("DeckId", "Position");

                    b.ToTable("deck_cards", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.PlayerRating", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Losses")
                        .HasColumnType("integer")
                        .HasColumnName("losses");

                    b.Property<int>("RatingValue")
                        .HasColumnType("integer")
                        .HasColumnName("rating_value");

                    b.Property<string>("Region")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("global")
                        .HasColumnName("region");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.HasKey("Id");

                    b.HasIndex("RatingValue")
                        .IsDescending();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ratings", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.ReplayLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ActionData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("action_data");

                    b.Property<int>("ActionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("action_number");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("match_id");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player_id");

                    b.HasKey("Id");

                    b.ToTable("replay_logs", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.UserAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.CardAbilityDefinition", b =>
                {
                    b.HasOne("CardDuel.ServerApi.Infrastructure.Models.AbilityDefinition", "AbilityDefinition")
                        .WithMany("CardAbilities")
                        .HasForeignKey("AbilityDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardDuel.ServerApi.Infrastructure.Models.CardDefinition", "CardDefinition")
                        .WithMany("CardAbilities")
                        .HasForeignKey("CardDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbilityDefinition");

                    b.Navigation("CardDefinition");
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.EffectDefinition", b =>
                {
                    b.HasOne("CardDuel.ServerApi.Infrastructure.Models.AbilityDefinition", "AbilityDefinition")
                        .WithMany("Effects")
                        .HasForeignKey("AbilityDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbilityDefinition");
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.DeckCard", b =>
                {
                    b.HasOne("CardDuel.ServerApi.Infrastructure.Models.CardDefinition", "CardDefinition")
                        .WithMany()
                        .HasForeignKey("CardDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CardDuel.ServerApi.Infrastructure.Models.PlayerDeck", "Deck")
                        .WithMany("DeckCards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardDefinition");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.GameRulesetSeatOverride", b =>
                {
                    b.HasOne("CardDuel.ServerApi.Infrastructure.Models.GameRuleset", "GameRuleset")
                        .WithMany("SeatOverrides")
                        .HasForeignKey("GameRulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameRuleset");
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.MatchmakingModeRulesetAssignment", b =>
                {
                    b.HasOne("CardDuel.ServerApi.Infrastructure.Models.GameRuleset", "Ruleset")
                        .WithMany("MatchmakingModeAssignments")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.PlayerRating", b =>
                {
                    b.HasOne("CardDuel.ServerApi.Infrastructure.Models.UserAccount", "User")
                        .WithOne("Rating")
                        .HasForeignKey("CardDuel.ServerApi.Infrastructure.Models.PlayerRating", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.PlayerDeck", b =>
                {
                    b.Navigation("DeckCards");
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.AbilityDefinition", b =>
                {
                    b.Navigation("CardAbilities");

                    b.Navigation("Effects");
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.CardDefinition", b =>
                {
                    b.Navigation("CardAbilities");
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.GameRuleset", b =>
                {
                    b.Navigation("MatchmakingModeAssignments");

                    b.Navigation("SeatOverrides");
                });

            modelBuilder.Entity("CardDuel.ServerApi.Infrastructure.Models.UserAccount", b =>
                {
                    b.Navigation("Rating");
                });
#pragma warning restore 612, 618
        }
    }
}
