global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'cardduel-monitor'

scrape_configs:
  - job_name: 'cardduel-api'
    static_configs:
      - targets: ['api:8080']
    metrics_path: '/metrics'
    scrape_interval: 300s
    scrape_timeout: 10s
