name: Deploy Raspberry

on:
  push:
    branches:
      - master

concurrency:
  group: deploy-raspberry
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: [self-hosted, linux, ARM64]

    steps:
      - name: Deploy on Raspberry
        run: /home/flippy/deploy-cardgameapi.sh